version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.7.5
    steps:
      - checkout
      - run:
          name: Run RSpec
          command: |
            gem install bundler -v 2.3.7
            bundle install
            bundle exec rake
      - run:
          name: Run Rubocop
          command: |
            gem install bundler -v 2.3.7
            bundle install
            bundle exec rubocop
