version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.7.5
    steps:
      - checkout
      - run:
          name: bundle install
          command: |
            gem install bundler -v 2.3.7
            bundle install
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec
      - run:
          name: Run Rubocop
          command: |
            bundle exec rubocop
